server:
  port: 8080

logging.config: "classpath:logback.xml"

spring:
  main.banner-mode: 'off'
  profiles:
    active: default

allowed.origins: "http://localhost:3000,http://domain.nav.no"

management:
  endpoints:
    web:
      base-path: /internal
      path-mapping.prometheus: /prometheus
      exposure:
        include: health,gateway,prometheus
